### ISSUE TITLE
Review schematic

### ISSUE THREAD

**Issue by MarelleV** [HCL-Hbot/universal_connector_board#1]
Could one or both take a look at the schematic? I mentioned some things in the 'notes' sections, please take a look at that.

**Comment by Hoog-V** [comment]
Hi Marelle, I have looked at your schematic. I added some missing connections and turned the GND symbols to the downward position. I have a tip when choosing your inductor; Look at the saturation current and not the max current rating. As the saturation current is the current at which your inductor starts losing inductance. So when designing for 5V 10A choose a inductor >12A saturation current.

Another thing that I stumbled up on are the pins reserved for the radar but not connected to anything, pin headers e.g.

Oh and have you tried checking the schematic using the [built-in erc checker](https://docs.kicad.org/master/en/getting_started_in_kicad/getting_started_in_kicad.html#electrical_rules_check) ?

**Comment by Hoog-V** [comment]
BTW; Wow! Good Job, I liked how structured your schematic is! It is better then the schematics I make! For the first PCB ever? I am proud of you!

Have a good weekend,

Victor

**Comment by MarelleV** [comment]
Thanks @Hoog-V ! I'll take a look at the things you mentioned. I appreciate the tip, sometimes I forget which data is most important for which component 😅 I'll try the built-in erc checker, i have not done that yet

**Comment by RichardKroesen** [comment]
Looks good and well organized. I like the Excel sheet ;) 
Here a couple of points of attention from me (the decision of what do to do with it is up to you):

But first off all just so you know, we cannot check all the details of the schematic. I just look quickly and check whether it makes sense, and go to the datasheet to check when in doubt. 

1. I would not recommend making the power inputs as a hierarchical label, because it is confusion.
![image](https://github.com/HCL-Hbot/universal_connector_board/assets/116025382/42cd4c3d-9426-4b47-858d-0229e20c0557)
But I see why you did it. You can just use the global +12V inside the hierarchical sheet itself.
Btw, for regulators from a input source it does make sense so here I would do this as well. But maybe not call it 12V. Because are we for sure it is a clean 12V source? 
![image](https://github.com/HCL-Hbot/universal_connector_board/assets/116025382/30deb1ff-fa8e-4acc-a5dc-e98c056f7eb8)
2. Place the power labels, please upright (yeah details haha)
![image](https://github.com/HCL-Hbot/universal_connector_board/assets/116025382/c8de2819-471c-4654-9d41-d0a466b5fe3f)
And because I'm already picky, also place the grounds always downwards:P.

 3. Just split this circuit, maybe you wanted to keep them together but it is not really at first look.
 
![image](https://github.com/HCL-Hbot/universal_connector_board/assets/116025382/293537f3-bccd-4e03-bd31-a4df56ef351c)
4. This is just a WIP err but just to note it:
![image](https://github.com/HCL-Hbot/universal_connector_board/assets/116025382/86c9a308-dac1-4f27-b152-b0be34893aca)
5. Make a custom footprint component of this. 
![image](https://github.com/HCL-Hbot/universal_connector_board/assets/116025382/3063ae18-561c-4d53-81ac-8f83a024535b)
For me this is a MUST to do, because if someone wants to reuse it, it should be well defined as a footprint. 

6. In the notes you mentioned about the layout and routing, here is what I think is a good idea in big lines:
![image](https://github.com/HCL-Hbot/universal_connector_board/assets/116025382/3725db0e-5d93-4599-aede-71a0574b01ac)
But again, I was just playing around so I didn't carefully looked at where for example the wifi IC of RPI4 is located which might be disturbed now.
In general I would do this:
- Layout in big lines your components, and start thinking in sections as I did above. 
- Start implementing your circuits, for example the regulators and finish them. Keep them appart from the rest! 
- Finish other sections.
- Start integrating and fine-tuning. 
- Place inputs and outputs together. 
- Place additional text labels for easier connectivity later. 
7. Can you add just in case a HW bouncing elements here
![image](https://github.com/HCL-Hbot/universal_connector_board/assets/116025382/458381c6-ad83-46af-97d2-dc6ce1ba7982)
8. Radar connector: I mis him :( haha yeah it is not properly implemented but will be some day XD
All in all a well looking schematic already,
